nodeLinker: node-modules

packageExtensions:
  "@backstage/cli@*":
    dependencies:
      form-data: ^4.0.4
  axios@*:
    dependencies:
      form-data: ^4.0.4
  jsdom@*:
    dependencies:
      form-data: ^4.0.4
