nodeLinker: node-modules

packageExtensions:
  "@backstage/cli@*":
    dependencies:
      form-data: ^4.0.4
  axios@*:
    dependencies:
      form-data: ^4.0.4
  jsdom@*:
    dependencies:
      form-data: ^4.0.4
  request@*:
    dependencies:
      form-data: ^4.0.4
  "@types/request@*":
    dependencies:
      form-data: ^4.0.4
  superagent@*:
    dependencies:
      form-data: ^4.0.4
  "@types/superagent@*":
    dependencies:
      form-data: ^4.0.4

yarnPath: .yarn/releases/yarn-4.9.4.cjs
